config/routes.rb
Rails.application.routes.draw do
	root 'products#index'
	resources :products 

end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: {maximum: 32}, allow_blank: true
  validates :cost, length: {maximum: 32}, allow_blank: true
  validates :description, length: {maximum: 32}, allow_blank: true

	has_one_attached :image
	
  
end

app/controllers/products_controller.rb
class ProductsController < BaseController

	def index
   	@page_title = "Products | Home"
   	get_collection
	end
	
	def Products
    @products=Product.all
	end

  def new
    new_product
   	@page_title = "Products | New Product"   
	end
	
	def show
		@product=Product.find(params[:id])
	end
	
	def edit
		@product=Product.find(params[:id])
   	@page_title = "Product | Update Product"   	
	end
  
  def create
	 	@product=Product.new(permitted_params)
    if @product.valid?
      @product.save
      set_notification(true, I18n.t('status.success'), I18n.t('success.created', item: "Products"))
	 	else
      message = I18n.t('errors.failed_to_create', item: "Products")     
      set_notification(false, I18n.t('status.error'), message)
	 	end
	end

	def update
    @product=Product.find(params[:id])
	  @product.update(permitted_params)
	  if @product.save
      set_notification(true, I18n.t('status.success'), I18n.t('success.updated', item: "Products"))
		else
      message = I18n.t('errors.failed_to_create', item: "Products")     
      set_notification(false, I18n.t('status.error'), message)
		end
	end
	
  def destroy
		@product=Product.find(params[:id])
		@product.destroy
		redirect_to @product
  end
    
  # --------------
  # Fetch Methods
  # --------------

	private

	def permitted_params
    params.require(:product).permit(:name, :cost, :description, :image, :title, :category, :sale_item, :t_c_accepted)
	end

  def new_product
    @product = Product.new
  end

  def existing_product
    @product = Product.find_by_id(params[:id])
  end

  def get_collection
    @relation = Product.where("")

    apply_filters

    @order_by = "created_at ASC" unless @order_by
    @products = @r_objects = @relation.order(@order_by).all #page(@current_page).per(@per_page)
  end
  
  def apply_filters
    @query = params[:q]
    @relation = @relation.search(@query) if @query && !@query.blank?
    #@relation = @relation.search_only_name(params[:filters].try(:[], :name))
    
  end

  def initialise_urls
    @wf_refresh_url = root_path
  end


end

app/views/layouts/product/_breadcrumbs.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to '+ Add New Product', new_product_path, :class =>"btn btn-success", :remote => true %>
  </div>
</div>          
<br>

app/views/layouts/product/_footer.html.erb
<div class="footer">
  <p>© 2020 Copyright:</p>
</div>

app/views/layouts/product/_head.html.erb
<head>
  <title><%= @page_title || "SampleProject" %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

app/views/layouts/product/_header.html.erb
<nav class="navbar" style="background-color: black; ">
  <a class="navbar-brand navbar-light mx-auto" href="#" style="align-content: center; color: #ffffff;">CRUD</a>
</nav>

app/views/layouts/product/_script.html.erb
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>