config/routes.rb
Rails.application.routes.draw do
	root 'products#index'
	resources :products 

end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: {maximum: 32}, allow_blank: true
  validates :cost, length: {maximum: 32}, allow_blank: true
  validates :description, length: {maximum: 32}, allow_blank: true

	has_one_attached :image
	
  
end

app/controllers/products_controller.rb
class ProductsController < BaseController

	def index
   	@page_title = "Products | Home"
   	get_collection
	end
	
	def Products
    @products=Product.all
	end

  def new
    new_product
   	@page_title = "Products | New Product"   
	end
	
	def show
		@product=Product.find(params[:id])
	end
	
	def edit
		@product=Product.find(params[:id])
   	@page_title = "Product | Update Product"   	
	end
  
  def create
	 	@product=Product.new(permitted_params)
    if @product.valid?
      @product.save
      set_notification(true, I18n.t('status.success'), I18n.t('success.created', item: "Products"))
	 	else
      message = I18n.t('errors.failed_to_create', item: "Products")     
      set_notification(false, I18n.t('status.error'), message)
	 	end
	end

	def update
    @product=Product.find(params[:id])
	  @product.update(permitted_params)
	  if @product.save
      set_notification(true, I18n.t('status.success'), I18n.t('success.updated', item: "Products"))
		else
      message = I18n.t('errors.failed_to_create', item: "Products")     
      set_notification(false, I18n.t('status.error'), message)
		end
	end
	
  def destroy
		@product=Product.find(params[:id])
		@product.destroy
		redirect_to @product
  end
    
  # --------------
  # Fetch Methods
  # --------------

	private

	def permitted_params
    params.require(:product).permit(:name, :cost, :description, :image, :title, :category, :sale_item, :t_c_accepted)
	end

  def new_product
    @product = Product.new
  end

  def existing_product
    @product = Product.find_by_id(params[:id])
  end

  def get_collection
    @relation = Product.where("")

    apply_filters

    @order_by = "created_at ASC" unless @order_by
    @products = @r_objects = @relation.order(@order_by).all #page(@current_page).per(@per_page)
  end
  
  def apply_filters
    @query = params[:q]
    @relation = @relation.search(@query) if @query && !@query.blank?
    #@relation = @relation.search_only_name(params[:filters].try(:[], :name))
    
  end

  def initialise_urls
    @wf_refresh_url = root_path
  end


end

app/views/products/create.js.erb
<% if @product.errors.blank? %>

  // Showing Growl Like Message
  notifySuccess("<%= escape_javascript(@notification[:title]) %>", "<%= escape_javascript(@notification[:message]) %>");
  
   $('#products_popup').modal('hide');
   window.location.replace("<%= root_path %>");
<% else %>

  // Showing Growl Like Message
  notifyError("<%= escape_javascript(@notification[:title]) %>", "<%= escape_javascript(@notification[:message]) %>");

<% end %>

app/views/products/edit.js.erb
$("#GENERIC_MODAL_DIV").html("<%= escape_javascript(render(:partial=>"products/edit/edit.html.erb")) %>");

$('#products_popup').modal('show');

app/views/products/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h2">Home / Products</h2>
  </div>
  <%= render partial: 'layouts/product/breadcrumbs' %>
    <div class="row">
      <% @products.each_with_index do |products, i| %>
        <div class="column">
          <div class="card" style="width: 25rem; height: 25rem;">
            <% if products.image.attached? %>
              <%= image_tag products.image.variant(resize: "300x300")%>
            <% end %>  

            <div class="card-body" style="background-color: #34216C; color: white;">
              <h5 class="card-title"><%= i + 1 %> . <%=products.title%></h5>
              <p class="card-text"><%=products.category%></p>
              <p class="card-text"><%=products.sale_item%></p>
            </div>
            <ul class="list-group list-group-flush" style="background-color: #35D4F4;">
              <li class="list-group-item" style="background-color: #34216C; color: white;"><%=products.cost%></li>
            </ul>
            <div class="card-body" style="background-color: #9FD7E5; height: 2rem;">
              <%= link_to product_path(products), :class => "card-link" do %><i class="fa fa-eye"></i><% end %>
              <%= link_to edit_product_path(products),:class => "card-link",  :remote => true do %><i class="fa fa-edit" ></i><% end %>
              <%= link_to product_path(products),  data: {confirm: "Are you sure you want to delete this?"}, method: :delete , :class => "card-link" do %><i class="fa fa-trash"></i><% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div><br><br>
</main>

app/views/products/new.js.erb
$("#GENERIC_MODAL_DIV").html("<%= escape_javascript(render(:partial=>"products/new/new.html.erb")) %>");

$('#products_popup').modal('show');

app/views/products/show.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h2">Home / Products</h2>
  </div>
    <div class="row">
      <div class="col-md-9">
        <h3>Products - <%=@product.id%></h3>
        <div class="card" align="align-items-center">
          <h5 class="card-header" style="background-color: #35D4F4;"><%=@product.name%></h5>
          <div class="card-body" style="background: #D2F4FB;">
            <div class="row" >
              <div class="column"> 
                <% if @product.image.attached? %>
                  <%= image_tag @product.image.variant(resize: "300x400")%>
                <% end %>
              </div>
              <div class="colmn"> 
                <h5 class="card-text">Title :<%=@product.title%></h5>
                <p class="card-text">Category: <%=@product.category%></p>
                <p class="card-text">Description: <%=@product.description%></p>
                <p class="card-text">Item For Sale: <%=@product.sale_item%></p>
                <p class="card-text">Cost: <%=@product.cost%></p>
                <p class="card-text">Accepted T $ C :
                <% if @product.t_c_accepted == true %> 
                  Accepted 
                <% else %>
                  Not Accepted
                <% end %>
                </p>

              </div>
            </div>
          </div>
          <div class="card-footer" style="background-color: #35D4F4;"><%= link_to 'Go Back' ,root_path, :class =>"btn btn-primary"  %></div>   
        </div>
      </div>
    </div>
</main>

app/views/products/update.js.erb
 <% if @notification[:success] %>
    notifySuccess("<%= escape_javascript(@notification[:title]) %>", "<%= escape_javascript(@notification[:message]) %>");
    $('#products_popup').modal('hide');
    window.location.href ="<%= root_path %>"

  <% else %>
    notifyError("<%= escape_javascript(@notification[:title]) %>", "<%= escape_javascript(@notification[:message]) %>");
    window.location.href ="<%= root_path %>"

  <% end %>

  